name: Windows Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build (One-Dir)
        run: python build_installer.py

      - name: Zip One-Dir
        shell: pwsh
        run: |
          Set-Location dist
          if (Test-Path RoloMemo) { Compress-Archive -Path RoloMemo -DestinationPath RoloMemo-Windows-OneDir.zip -Force }

      - name: Build (One-File)
        env:
          ROLOMEMO_ONEFILE: '1'
        run: python build_installer.py

      - name: Zip One-File
        shell: pwsh
        run: |
          Set-Location dist
          if (Test-Path RoloMemo.exe) { Compress-Archive -Path RoloMemo.exe -DestinationPath RoloMemo-Windows-OneFile.zip -Force }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoloMemo-Windows
          path: |
            dist/RoloMemo-Windows-OneDir.zip
            dist/RoloMemo-Windows-OneFile.zip
          if-no-files-found: warn

      - name: Create GitHub Release (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/RoloMemo-Windows-OneDir.zip
            dist/RoloMemo-Windows-OneFile.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
